DATABASE_NAME = 'twitter-archive'
COLLECTION_NAME = 'tweets'
TAGS = ['mongodb', 'ruby']
DATABASE_ADDRS = ['10.34.0.4:27017']

#TWITTER CONFIG
CONSUMER_KEY        = "KEYS_FROM_TWITTER_APP"
CONSUMER_SECRET     = "KEYS_FROM_TWITTER_APP"
ACCESS_TOKEN        = "KEYS_FROM_TWITTER_APP"
ACCESS_TOKEN_SECRET = "KEYS_FROM_TWITTER_APP"